name: random_shapes_animator
description: "A fully customizable Flutter widget that adds sparkling or animated shapes such as stars, circles, or snowflakes to any widget. Great for festive UIs, celebration screens, birthdays, holidays, special events, or decorative effects. Designed to be lightweight, smooth, and highly performant. Easily integrate dynamic, beautiful animated elements into your app without heavy performance costs. Perfect for enhancing user interfaces with interactive, lively, and eye-catching visual animations."
version: 1.0.1
homepage: https://github.com/priyanshudutta04/RandomShapesAnimator.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
