name: random_shapes_animator
description: "Random Shapes Animator Package"
version: 1.0.0
homepage: https://github.com/priyanshudutta04/RandomShapesAnimator.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
